const mongoose = require('mongoose')
const { dbURI } = require('./config/environment')
const User = require('./models/User')
const Vinyl = require('./models/Vinyl')

mongoose.connect(dbURI, (err, db) => {
  db.dropDatabase()
    .then(() => {
      User.create({
        username: 'seangray1',
        email: 'sean.myles.gray@gmail.com',
        password: 'pass',
        passwordConfirmation: 'pass'
      })
    })
    .then(() => {
      return Vinyl.create([{
        artist: 'Childish Gambino',
        title: 'Awaken, My Love',
        image: 'https://img.discogs.com/wAATX_t7ex9676wTKZudRnFzpi0=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-10288421-1495025633-4438.jpeg.jpg',
        releaseYear: 2017,
        genre: 'Funk',
        condition: 'Mint',
        length: '48:57',
        notes: '"Awaken, My Love!" is the third studio album by American rapper Donald Glover',
        label: 'Glassnote',
        size: '12"',
        format: '2LP',
        speed: '45 RPM',
        catalogueNumber: 'GLS-0209-01',
        barcode: 810599021412
      },{
        artist: 'A Tribe Called Quest',
        title: 'The Low End Theory',
        image: 'https://img.discogs.com/Na_71Y9oc_wwixsjzafZhfDWQZA=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-94800-1467721235-8229.jpeg.jpg',
        releaseYear: 1991,
        genre: 'Hip-Hop',
        condition: 'Mint',
        length: '48:03',
        notes: 'The Low End Theory is the second studio album by American hip hop group A Tribe Called Quest',
        label: 'Jive',
        size: '12"',
        format: '1LP',
        speed: '45 RPM',
        catalogueNumber: '1418-1-JDJ',
        barcode: 3562749401700
      },{
        artist: 'Slayer',
        title: 'Reign In Blood',
        image: 'https://img.discogs.com/PAvYnD9WYdKCdkDZW2-X6erkIkk=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-377521-1262974365.jpeg.jpg',
        releaseYear: 1986,
        genre: 'Heavy Metal',
        condition: 'Mint',
        length: '25:58',
        notes: 'KILL KIILLL KIIIILLLLLLKIKIKIKKK KKKKKKKKKKK',
        label: 'Def Jam Recordings',
        size: '12"',
        format: '1LP',
        speed: '45 RPM',
        catalogueNumber: 'GHS 24131',
        barcode: 6007535010540
      },{
        artist: 'Ornette Coleman',
        title: 'The Shape Of Jazz To Come',
        image: 'https://img.discogs.com/Px82OSzDFGt3wHlYP_Fpwqlgkx0=/fit-in/600x591/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-488973-1537684103-9468.jpeg.jpg',
        releaseYear: 1959,
        genre: 'Jazz',
        condition: 'Mint',
        length: '37:59',
        notes: 'The Shape of Jazz to Come is the third album by jazz musician Ornette Coleman.',
        label: 'Atlantic',
        size: '12"',
        format: '2LP',
        speed: '45 RPM',
        catalogueNumber: 'ATL-5038',
        barcode: 7567813392
      },{
        artist: 'Chaka Khan',
        title: 'Hello Happiness',
        image: 'https://img.discogs.com/dHxCBaAyLanM4rA4rgze0riI0cQ=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-13202042-1550059790-4542.jpeg.jpg',
        releaseYear: 2019,
        genre: 'Pop',
        condition: 'Mint',
        length: '27:10',
        notes: 'Hello Happiness is the twelfth studio album by American singer Chaka Khan, released on February 15, 2019. It is her first new material since 2007s Funk This. On limited coral coloured vinyl.',
        label: 'Island Records',
        size: '12"',
        format: '1LP',
        speed: '45 RPM',
        catalogueNumber: '7738531',
        barcode: 602577385315
      },{
        artist: 'Robyn',
        title: 'Honey',
        image: 'https://images-na.ssl-images-amazon.com/images/I/61WaZwHl3iL._SL1200_.jpg',
        releaseYear: 2018,
        genre: 'Pop',
        condition: 'Mint',
        length: '40:23',
        notes: 'Honey is the eighth studio album by Swedish singer Robyn, and her first since Body Talk (2010). It was released on 26 October 2018 through Konichiwa and Island Records. It features the singles "Missing U", "Honey" (a version of which originally featured in the final season of the HBO series Girls in 2017), and "Send to Robin Immediately"',
        label: 'Island Records',
        size: '12"',
        format: '1LP',
        speed: '45 RPM',
        catalogueNumber: 'KOR057LP',
        barcode: 602567994688
      },{
        artist: 'Nancy Wilson/Cannonball Adderley',
        title: 'Nancy Wilson/Cannonball Adderley',
        image: 'https://img.discogs.com/btZmvTz5WSAG_MlJuwWGPymhIpU=/fit-in/469x471/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-6519284-1421090801-1744.jpeg.jpg',
        releaseYear: 1961,
        genre: 'Jazz',
        condition: 'Fair',
        length: '41:34',
        notes: 'Nancy Wilson/Cannonball Adderley is a studio album by Nancy Wilson and Cannonball Adderley issued in February 1962 by Capitol Records.',
        label: 'Capitol Records',
        size: '12"',
        format: '1LP',
        speed: '45 RPM',
        catalogueNumber: 'ST-1657',
        barcode: 123456789
      },{
        artist: 'St Vincent',
        title: 'St Vincent',
        image: 'https://images-na.ssl-images-amazon.com/images/I/91mV8CQIoCL._SL1200_.jpg',
        releaseYear: 2014,
        genre: 'Alternative Rock',
        condition: 'Mint',
        length: '40:04',
        notes: 'St. Vincent is the eponymous fourth studio album by American musician St. Vincent. The album won a 2015 Grammy Award for Best Alternative Album, making St. Vincent only the second female solo artist to win the award since its inception in 1991.',
        label: 'Loma Vista',
        size: '12"',
        format: '2LP',
        speed: '45 RPM',
        catalogueNumber: 'UNIW40355',
        barcode: 60253672509
      },{
        artist: 'Radiohead',
        title: 'In Rainbows',
        image: 'https://img.discogs.com/hldHd6xXfRrbYVgHDByRoNS8Pnw=/fit-in/600x586/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1187003-1495677239-2816.jpeg.jpg',
        releaseYear: 2007,
        genre: 'Alternative Rock',
        condition: 'Mint',
        length: '42:39',
        notes: 'n Rainbows is the seventh studio album by English rock band Radiohead. It was self-released on 10 October 2007 as a pay-what-you-want download, followed by a physical release internationally by XL Recordings in December 2007.',
        label: 'XL Recordings',
        size: '12"',
        format: '1LP',
        speed: '45 RPM',
        catalogueNumber: 'XLLP 324',
        barcode: 880882162313
      },{
        artist: 'D\'Aneglo',
        title: 'Brown Sugar',
        image: 'https://img.discogs.com/qhZuVZb8wSWqKmvuJioQwzJsxTA=/fit-in/500x500/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-3997782-1419865751-1816.jpeg.jpg',
        releaseYear: 1995,
        genre: 'RnB',
        condition: 'Mint',
        length: '53:17',
        notes: 'Brown Sugar is the debut studio album by American R&B singer, songwriter, and multi-instrumentalist D\'Angelo. It was released on July 3, 1995, by EMI Music.',
        label: 'EMI',
        size: '12"',
        format: '2LP',
        speed: '45 RPM',
        catalogueNumber: '4724081',
        barcode: 602547240811
      },{
        artist: 'Kendrick Lamar',
        title: 'Damn',
        image: 'https://img.discogs.com/7DbnFpfKBhaeQT1Mac1c4j-2xPI=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-10133538-1492204963-3196.jpeg.jpg',
        releaseYear: 2017,
        genre: 'Hip-Hop',
        condition: '',
        length: '54:54',
        notes: 'Damn (stylized as DAMN.) is the fourth studio album by American rapper Kendrick Lamar. It was released on April 14, 2017, by Aftermath Entertainment, Interscope Records and Top Dawg Entertainment.',
        label: 'Polydor',
        size: '12"',
        format: '2LP',
        speed: '45 RPM',
        catalogueNumber: '5761828',
        barcode: 602557618280
      },{
        artist: 'Glass Animals',
        title: 'How To Be A Human Being',
        image: 'https://img.discogs.com/X8PCjcUCHzy7OcpOtcWgtK8YjZ8=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-8959209-1472259764-3090.jpeg.jpg',
        releaseYear: 2016,
        genre: 'Alternative Rock',
        condition: 'Mint',
        length: '43:16',
        notes: 'How to Be a Human Being is the second studio album by English indie rock group Glass Animals.',
        label: 'Wolf Tone',
        size: '12"',
        format: '2LP',
        speed: '45 RPM',
        catalogueNumber: 'WOLFTONE012LP',
        barcode: 602547950871
      },{
        artist: 'Kate Tempest',
        title: 'Let Them Eat Chaos',
        image: 'https://img.discogs.com/s_d4kK62gByTCI3Kt1YTZLFKeIc=/fit-in/600x539/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-9478028-1487369532-2802.jpeg.jpg',
        releaseYear: 2017,
        genre: 'Hip-Hop',
        condition: 'Mint',
        length: '47:43',
        notes: 'Let Them Eat Chaos is the second studio album by English poet and spoken word artist Kate Tempest, the follow up to her Mercury Prize-nominated debut Everybody Down.',
        label: 'Fiction Records',
        size: '12"',
        format: '2LP',
        speed: '45 RPM',
        catalogueNumber: 'CHAOS23',
        barcode: 602557128277
      },{
        artist: 'Taylor Swift',
        title: '1989',
        image: 'https://img.discogs.com/dZ9Nb-FAwkBTYrmrL4yTeC2-8FY=/fit-in/600x530/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-10163220-1522357384-7574.jpeg.jpg',
        releaseYear: 2014,
        genre: 'Pop',
        condition: 'Mint',
        length: '48:41',
        notes: '1989 is the fifth studio album by American singer-songwriter Taylor Swift, released on October 27, 2014 through Big Machine Records.',
        label: 'Virgin EMI',
        size: '12"',
        format: '2LP',
        speed: '45 RPM',
        catalogueNumber: 'LC01846',
        barcode: 602547092687
      },{
        artist: 'Tame Impala',
        title: 'Currents',
        image: 'https://img.discogs.com/M0FsreRJsuTyo3yKEoDoHuRiIPA=/fit-in/596x540/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-7266433-1510163886-8146.jpeg.jpg',
        releaseYear: 2015,
        genre: 'Alternative Rock',
        condition: 'Mint',
        length: '51:06',
        notes: 'Currents is the third studio album by Australian artist Tame Impala. It was released on 17 July 2015 by Modular Recordings and Universal Music Australia, Interscope Records in the United States, and Fiction Records and Caroline International in other international regions. Like the group\'s previous two albums, Currents was written, recorded, performed, and produced by primary member Kevin Parker.',
        label: 'Fiction Records',
        size: '12"',
        format: '2LP',
        speed: '45 RPM',
        catalogueNumber: '4730677',
        barcode: 602547306777
      },{
        artist: 'Sam Cooke',
        title: 'Portrait Of A Legend',
        image: 'https://img.discogs.com/VMbwXf4TVLroPShGxbKWy3PCue4=/fit-in/600x589/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-986910-1181048807.jpeg.jpg',
        releaseYear: 2003,
        genre: 'RnB',
        condition: 'Mint',
        length: '79:08',
        notes: 'Portrait of a Legend: 1951–1964 is a compilation album by American singer-songwriter Sam Cooke, released posthumously on June 17, 2003 by ABKCO Records. The disc covers Cooke\'s entire career, from his early 1950s beginnings with the Soul Stirrers to the posthumous 1964 single "Shake".',
        label: 'ABKCO Music & Records Ltd',
        size: '12"',
        format: '2LP',
        speed: '45 RPM',
        catalogueNumber: 'LC22670',
        barcode: 18771926412
      },{
        artist: 'Count Basie and his orchestra',
        title: 'April in Paris',
        image: 'https://img.discogs.com/ujCySvZ8BymuPq5lIOeCMRixyVc=/fit-in/400x381/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-5147760-1385796678-9080.jpeg.jpg',
        releaseYear: 2013,
        genre: 'Jazz',
        condition: 'Mint',
        length: '37.43',
        notes: 'Reissue of April in Paris, the classic album by pianist and bandleader Count Basie and His Orchestra, his first released on the Verve label, recorded in 1955 and 1956.',
        label: 'Verve',
        size: '12"',
        format: '1LP',
        speed: '45 RPM',
        catalogueNumber: '5345893',
        barcode: 600753458938
      },{
        artist: 'John Coltrane',
        title: 'Both Directions At Once: The Lost Album',
        image: 'https://img.discogs.com/fMOX-VMDd710gsPFdj7kRDlc0S0=/fit-in/600x531/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-12191700-1534937036-8133.jpeg.jpg',
        releaseYear: 2018,
        genre: 'Jazz',
        condition: 'Mint',
        length: '77:63',
        notes: 'Both Directions at Once: The Lost Album is a studio album recorded by saxophonist John Coltrane for Impulse! Records that was first released in 2018. The recordings were made in 1963 during Coltrane\'s Classic Quartet period and lost for decades.',
        label: 'Impulse!',
        size: '12"',
        format: '2LP',
        speed: '45 RPM',
        catalogueNumber: '6749301',
        barcode: 602567493013
      },{
        artist: 'Chris Stapleton',
        title: 'Traveller',
        image: 'https://img.discogs.com/rdqOLwMgiZPF_p7GyX58f981rm8=/fit-in/600x541/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-6987728-1524693525-7221.jpeg.jpg',
        releaseYear: 2015,
        genre: 'Country',
        condition: 'Mint',
        length: '63:04',
        notes: 'Traveller is the debut studio album by American singer-songwriter Chris Stapleton. The album was produced by Dave Cobb and Stapleton, and was released on May 5, 2015, through Mercury Nashville.',
        label: 'Mercury Nashville',
        size: '12"',
        format: '2LP',
        speed: '45 RPM',
        catalogueNumber: '4725522',
        barcode: 602547255228
      },{
        artist: 'Amy Winehouse',
        title: 'Back To Black',
        image: 'https://img.discogs.com/cPCB4YLC5A7PehUrvVZtPVyvVlY=/fit-in/600x589/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-825438-1194731140.jpeg.jpg',
        releaseYear: 2006,
        genre: 'Pop',
        condition: 'Mint',
        length: '34:56',
        notes: 'Back to Black is the second and final studio album by English singer and songwriter Amy Winehouse. It was released on 27 October 2006 by Island Records. The album spawned five singles: "Rehab", "You Know I\'m No Good", "Back to Black", "Tears Dry on Their Own" and "Love Is a Losing Game". Back to Black was acclaimed by music critics, who praised Winehouse\'s songwriting and emotive singing style as well as Salaam Remi and Mark Ronson\'s production.',
        label: 'Island Records',
        size: '12"',
        format: '1LP',
        speed: '45 RPM',
        catalogueNumber: '1734128',
        barcode: 602517341289
      },{
        artist: 'Max Richter',
        title: 'Recomposed: Vivaldi - The Four Seasons',
        image: 'https://img.discogs.com/yorrrOY7MswBrxzqHcBvJO-PV-g=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-6175289-1412950226-7930.jpeg.jpg',
        releaseYear: 2017,
        genre: 'Classical',
        condition: 'Near-Mint',
        length: '43:58',
        notes: 'Recomposed by Max Richter: Vivaldi – The Four Seasons is the 2012 album by neo-classical composer Max Richter, released on August 31, 2012 on Universal Classics and Jazz (Germany), a division of Universal Music Group, and Deutsche Grammophon.',
        label: 'Deutsche Grammophon',
        size: '12"',
        format: '2LP',
        speed: '45 RPM',
        catalogueNumber: '4793337',
        barcode: 28947933373
      },{
        artist: 'Bjork',
        title: 'Vulnicura',
        image: 'https://img.discogs.com/0MlEY37uYaLgRoOVBvewOTtzB0A=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-7165846-1437824309-6017.jpeg.jpg',
        releaseYear: 2015,
        genre: 'Pop',
        condition: 'Mint',
        length: '58:36',
        notes: 'Vulnicura is the eighth studio album by Icelandic musician and singer Björk. It was produced by Björk, Arca and The Haxan Cloak, and released on 20 January 2015 by One Little Indian Records. Björk said the album expresses her feelings before and after her breakup with American contemporary artist Matthew Barney and the healing process.',
        label: 'One Little Indian',
        size: '12"',
        format: '2LP',
        speed: '45 RPM',
        catalogueNumber: 'LC 03275',
        barcode: 5016958998271
      },{
        artist: 'Nina Simone',
        title: 'I Put A Spell On You',
        image: 'https://img.discogs.com/5UzVkJ-sHfMRqUsw2BtkJQPX5l4=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1337678-1472514305-4913.png.jpg',
        releaseYear: 2017,
        genre: 'Jazz',
        condition: 'Mint',
        length: '34:21',
        notes: 'Reissue of I Put a Spell on You, studio album by American jazz singer, songwriter, and pianist Nina Simone. Recorded in 1964 and 1965 in New York City, it was released by Philips Records in 1965.',
        label: 'Philips',
        size: '12"',
        format: '1LP',
        speed: '45 RPM',
        catalogueNumber: '5360570',
        barcode: 600753605707
      },{
        artist: 'Stevie Wonder',
        title: 'Innervisions',
        image: 'https://img.discogs.com/hKYhhcE5coVNKLjcNPi9QMTZti4=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-13286331-1551400916-4169.jpeg.jpg',
        releaseYear: 1973,
        genre: 'Funk',
        condition: 'Near-Mint',
        length: '44:12',
        notes: 'Innervisions is the 16th studio album by American musician Stevie Wonder, released August 3, 1973, on the Tamla label for Motown Records, a landmark recording of his "classic period".',
        label: 'Motown Records',
        size: '12"',
        format: '1LP',
        speed: '45 RPM',
        catalogueNumber: 'LC00881',
        barcode: 50109032617
      },{
        artist: 'The Weeknd',
        title: 'Starboy',
        image: 'https://img.discogs.com/sgpeelvWqv7LI3cw9Cmpbi9cMKU=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-9804601-1487020408-6474.jpeg.jpg',
        releaseYear: 2017,
        genre: 'RnB',
        condition: 'Mint',
        length: '68:40',
        notes: 'Starboy is the third studio album by Canadian singer The Weeknd. It was released on November 25, 2016, by Republic Records and XO. The album features guest appearances from Daft Punk, Lana Del Rey, Kendrick Lamar and Future. Translucent red vinyl.',
        label: 'XO, Republic Records',
        size: '12"',
        format: '2LP',
        speed: '45 RPM',
        catalogueNumber: '5722751',
        barcode: 602557227512
      },{
        artist: 'David Brent & Foregone Conclusion',
        title: 'Lady Gypsy / Life On The Road',
        image: 'https://img.discogs.com/DnbsP2OWsu8tXzXOx700FqjpgoY=/fit-in/500x500/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-8937502-1471831863-5552.jpeg.jpg',
        releaseYear: 2016,
        genre: 'Rock & Roll',
        condition: 'Near-Mint',
        length: '5:23',
        notes: 'Two lead singles from David Brent: Life on the Road, soundtrack to the 2016 British mockumentary comedy film written, directed, and produced by Ricky Gervais and released by Entertainment One.',
        label: 'Caroline International',
        size: '7"',
        format: '1LP',
        speed: '45 RPM',
        catalogueNumber: '5702631',
        barcode: 602557026313
      }])
    })
})
